// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"
#include "Arduino.h"
#include "ui_helpers.h"
#include "ui_events.h"
void play_Animation(lv_obj_t * TargetObject, int delay);
void play2_Animation(lv_obj_t * TargetObject, int delay);


// SCREEN: ui_back
void ui_back_screen_init(void);
void ui_event_back(lv_event_t * e);
extern lv_obj_t * ui_back;
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
void ui_event_Screen1(lv_event_t * e);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_yuang;
extern lv_obj_t * ui_logo;
extern lv_obj_t * ui_yuang1;
void anim_end_cb(lv_anim_t * anim);
// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
void ui_event_Screen2(lv_event_t * e);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_Watchback;
extern lv_obj_t *ui_elecrow1;
extern lv_obj_t *ui_AmPm;
extern lv_obj_t * ui_shand;
extern lv_obj_t * ui_mhand;
void ui_event_hhand(lv_event_t * e);
extern lv_obj_t * ui_hhand;

// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
void ui_event_Screen3(lv_event_t * e);

extern lv_obj_t * ui_Screen3;
extern lv_obj_t * ui_Watchback2;
extern lv_obj_t *ui_elecrow2;
extern lv_obj_t *ui_AmPm2;
extern lv_obj_t * ui_shand2;
extern lv_obj_t * ui_mhand2;
extern lv_obj_t * ui_hhand2;
// SCREEN: ui_Screen4
void ui_Screen4_screen_init(void);
void ui_event_Screen4(lv_event_t * e);
extern lv_obj_t * ui_Screen4;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Switch1;
extern lv_obj_t * ui_Dropdown1;
extern lv_obj_t * ui_Dropdown2;
extern lv_obj_t * ui_minuteLabel;
extern lv_obj_t * ui_hourLabel;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui____initial_actions0;

// SCREEN: ui_Screen5
void ui_Screen5_screen_init(void);
extern lv_obj_t *ui_Screen5;
void ui_event_Screen5( lv_event_t * e);
extern lv_obj_t *ui_Image1;
extern lv_obj_t *ui_Label1;
extern lv_obj_t *ui____initial_actions0;

LV_IMG_DECLARE(ui_img_1671030567);    // assets\Rainbow ring 240px.png
LV_IMG_DECLARE(ui_img_logo_60px_png);    // assets\logo 60px.png
LV_IMG_DECLARE( ui_img_81598846);   // assets\elecrow_logo_100-20px.png
LV_IMG_DECLARE(ui_img_312354278);    // assets\Rainbow ring 135px.png
LV_IMG_DECLARE(ui_img_1530809127);    // assets\01 dial plate240px.png
LV_IMG_DECLARE(ui_img_39728541);    // assets\01 Second hand update.png
LV_IMG_DECLARE(ui_img_327242551);    // assets\01 Minute hand updating.png
LV_IMG_DECLARE(ui_img_146052295);    // assets\01 Clockwise update.png
LV_IMG_DECLARE(ui_img_204151226);    // assets\02 dial plate 240px.png
LV_IMG_DECLARE(ui_img_1726273370);    // assets\second hand.png
LV_IMG_DECLARE(ui_img_1304719198);    // assets\minute hand.png
LV_IMG_DECLARE(ui_img_1608590414);    // assets\hour hand.png
LV_IMG_DECLARE(ui_img_1760865983);    // assets\Round bottom of alarm clock 240px.png
LV_IMG_DECLARE(ui_img_01_png); 
// Global variables are used to store switch states
extern bool switchState;
extern char  hour[32];
extern char  mimu[32];

//current time
extern uint32_t  m;
extern uint32_t  h;
extern uint32_t  s;
extern uint32_t  tmp1;
extern uint32_t Screen_flag;
//Travel time function
void time_refresh(lv_event_t* event);
void send_event(void);


static void switch_event_handler(lv_event_t *e);
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
