// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x040404), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_yuang = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_yuang, &ui_img_1671030567);
    lv_obj_set_width(ui_yuang, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_yuang, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_yuang, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_yuang, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_yuang, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_logo = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_logo, &ui_img_logo_60px_png);
    lv_obj_set_width(ui_logo, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_logo, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_logo, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_logo, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_logo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_yuang1 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_yuang1, &ui_img_312354278);
    lv_obj_set_width(ui_yuang1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_yuang1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_yuang1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_yuang1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_yuang1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_Screen1, ui_event_Screen1, LV_EVENT_ALL, NULL);

}
