// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"

void ui_Screen3_screen_init(void)
{
    ui_Screen3 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Watchback2 = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_Watchback2, &ui_img_204151226);
    lv_obj_set_width(ui_Watchback2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Watchback2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Watchback2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Watchback2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Watchback2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_elecrow2 = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_elecrow2, &ui_img_81598846);
    lv_obj_set_width( ui_elecrow2, 100);
    lv_obj_set_height( ui_elecrow2, 20);
    lv_obj_set_x( ui_elecrow2, 0 );
    lv_obj_set_y( ui_elecrow2, 42 );
    lv_obj_set_align( ui_elecrow2, LV_ALIGN_CENTER );
    lv_obj_add_flag( ui_elecrow2, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
    lv_obj_clear_flag( ui_elecrow2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
    
    ui_AmPm2 = lv_label_create(ui_Screen3);
    lv_obj_set_width( ui_AmPm2, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height( ui_AmPm2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x( ui_AmPm2, 40 );
    lv_obj_set_y( ui_AmPm2, -40 );
    lv_obj_set_align( ui_AmPm2, LV_ALIGN_CENTER );
    lv_label_set_text(ui_AmPm2,"AM");
    lv_obj_set_style_text_color(ui_AmPm2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_text_opa(ui_AmPm2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);



    ui_shand2 = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_shand2, &ui_img_1726273370);
    lv_obj_set_width(ui_shand2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_shand2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_shand2, 0);
    lv_obj_set_y(ui_shand2, -50);
    lv_obj_set_align(ui_shand2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_shand2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_shand2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_pivot(ui_shand2, 5,120 );//119
    lv_img_set_angle(ui_shand2, 100);

    ui_mhand2 = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_mhand2, &ui_img_1304719198);
    lv_obj_set_width(ui_mhand2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_mhand2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_mhand2, 0);
    lv_obj_set_y(ui_mhand2, -48);//
    lv_obj_set_align(ui_mhand2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_mhand2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_mhand2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_pivot(ui_mhand2,8,101 );//8, 100
    lv_img_set_angle(ui_mhand2, 100000);

    ui_hhand2 = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_hhand2, &ui_img_1608590414);
    lv_obj_set_width(ui_hhand2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_hhand2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_hhand2, 0);
    lv_obj_set_y(ui_hhand2, -30);
    lv_obj_set_align(ui_hhand2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_hhand2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_hhand2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_pivot(ui_hhand2,7,65);//8, 64
    lv_img_set_angle(ui_hhand2, 1800);

    lv_obj_add_event_cb(ui_Screen3, ui_event_Screen3, LV_EVENT_ALL, NULL);
}
