// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Watchback = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_Watchback, &ui_img_1530809127);
    lv_obj_set_width(ui_Watchback, lv_pct(100));
    lv_obj_set_height(ui_Watchback, lv_pct(100));
    lv_obj_set_align(ui_Watchback, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Watchback, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Watchback, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    
    ui_elecrow1 = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_elecrow1, &ui_img_81598846);
    lv_obj_set_width( ui_elecrow1, 100);
    lv_obj_set_height( ui_elecrow1, 20);
    lv_obj_set_x( ui_elecrow1, 0 );
    lv_obj_set_y( ui_elecrow1, 42 );
    lv_obj_set_align( ui_elecrow1, LV_ALIGN_CENTER );
    lv_obj_add_flag( ui_elecrow1, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
    lv_obj_clear_flag( ui_elecrow1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
    
    
    ui_AmPm = lv_label_create(ui_Screen2);
    lv_obj_set_width( ui_AmPm, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height( ui_AmPm, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x( ui_AmPm, 40 );
    lv_obj_set_y( ui_AmPm, -40 );
    lv_obj_set_align( ui_AmPm, LV_ALIGN_CENTER );
    lv_label_set_text(ui_AmPm,"AM");
    lv_obj_set_style_text_color(ui_AmPm, lv_color_hex(0xFDFDFD), LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_text_opa(ui_AmPm, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

    ui_shand = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_shand, &ui_img_39728541);
    lv_obj_set_width(ui_shand, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_shand, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_shand, 0);
    lv_obj_set_y(ui_shand, -33);
    lv_obj_set_align(ui_shand, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_shand, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_shand, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_pivot(ui_shand, 4, 119);
    
  
    ui_mhand = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_mhand, &ui_img_327242551);
    lv_obj_set_width(ui_mhand, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_mhand, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_mhand, 0);
    lv_obj_set_y(ui_mhand, -33);
    lv_obj_set_align(ui_mhand, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_mhand, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_mhand, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_pivot(ui_mhand, 3, 95);
    lv_img_set_angle(ui_mhand, 10000);

    ui_hhand = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_hhand, &ui_img_146052295);
    lv_obj_set_width(ui_hhand, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_hhand, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_hhand, 0);
    lv_obj_set_y(ui_hhand, -36);
    lv_obj_set_align(ui_hhand, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_hhand, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_hhand, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_pivot(ui_hhand, 7, 76);
    lv_img_set_angle(ui_hhand, 1000);

    lv_obj_add_event_cb(ui_hhand, ui_event_hhand, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Screen2, ui_event_Screen2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Screen2, time_refresh,LV_EVENT_REFRESH ,NULL);
    lv_timer_create((void*)send_event, 50, NULL);

}
